var classes = [
    {
        "name": "App\\Calculator",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "add",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "f",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getFib",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 3,
        "length": 27,
        "vocabulary": 14,
        "volume": 102.8,
        "difficulty": 4.44,
        "effort": 456.88,
        "level": 0.23,
        "bugs": 0.03,
        "time": 25,
        "intelligentContent": 23.13,
        "number_operators": 11,
        "number_operands": 16,
        "number_operators_unique": 5,
        "number_operands_unique": 9,
        "cloc": 0,
        "loc": 20,
        "lloc": 20,
        "mi": 57.26,
        "mIwoC": 57.26,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 5.33,
        "relativeSystemComplexity": 5.33,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 16,
        "totalSystemComplexity": 16,
        "package": "App\\",
        "pageRank": 0.5,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Database",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "connect",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "disconnect",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "PDO"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 11,
        "vocabulary": 7,
        "volume": 30.88,
        "difficulty": 2.67,
        "effort": 82.35,
        "level": 0.38,
        "bugs": 0.01,
        "time": 5,
        "intelligentContent": 11.58,
        "number_operators": 7,
        "number_operands": 4,
        "number_operators_unique": 4,
        "number_operands_unique": 3,
        "cloc": 1,
        "loc": 23,
        "lloc": 22,
        "mi": 75.89,
        "mIwoC": 60.02,
        "commentWeight": 15.87,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 2,
        "package": "App\\",
        "pageRank": 0.5,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    }
]